name: 'Apply helm chart to K8S'
description: 'After detecting change, use helm to apply chart.'

runs:
  using: "composite"
  steps:

    - name: Apply Chart to cluster
      shell: bash
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      run: |
        helmfile -f middleware/${{ inputs.chart_name }}/helmfile.yaml apply
