repositories:
- name: k8s-at-home
  url: https://k8s-at-home.com/charts/

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: owncast
    namespace: owncast
    chart: k8s-at-home/owncast
    version: 3.3.1
    values:
      - ./values.yaml
