repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: nginx
    namespace: ingress-controller
    chart: ingress-nginx/ingress-nginx
    version: 4.14.x
    values:
      - ./values.yaml
