repositories:
  - name: actions-runner-controller
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600


templates:
  default: &default
    missingFileHandler: Error
    namespace: gitops
    values:
      - "./values/{{ .Release.name }}.yaml"
    secrets:
      - "./secrets/{{ .Release.name }}.yaml"


releases:
  - name: arc-runner-controller
    chart: actions-runner-controller/gha-runner-scale-set-controller
    <<: *default
    version: 0.13.1

  - name: arc-runner-set
    chart: actions-runner-controller/gha-runner-scale-set
    <<: *default
    needs:
      - arc-runner-controller
    version: 0.13.1
