repositories:
  - name: actions-runner-controller
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: arc-runner-controller
    namespace: gitops
    chart: actions-runner-controller/gha-runner-scale-set-controller
    version: 0.13.x
    values:
      - ./values-controller.yaml

  - name: arc-runner-set
    namespace: gitops
    chart: actions-runner-controller/gha-runner-scale-set
    version: 0.13.x
    values:
      - ./values-runner.yaml
    secrets:
      - ./encrypted.yaml
