repositories:
- name: jetstack
  url: https://charts.jetstack.io

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.19.2
    values:
      - ./values.yaml
