repositories:
- name: jellyfin
  url: https://jellyfin.github.io/jellyfin-helm

helmDefaults:
  createNamespace: true
  wait: false
  timeout: 600

releases:
  - name: jellyfin
    namespace: streaming
    chart:  jellyfin/jellyfin
    version: 2.7.0
    values:
      - ./values.yaml
